### ISSUE TITLE
Test task question

### ISSUE THREAD

**Issue by marker-dao** [eduard-vm/nethernite-test-spa#1]
Добрый день. Не могли бы мы пообщаться по email (или любым удобным для вас способом) по поводу вашего тестового?

**Comment by eduard-vm** [comment]
Здравствуйте, вы кто?

вс, 7 мар. 2021 г., 01:18 Mertvye Dushi <notifications@github.com>:

**Comment by marker-dao** [comment]
Тоже соискатель. Делал тестовое в эту компанию на прошлой неделе (есть в репозиториях тут). О самой компании практически нигде ничего не написано и я наткнулся на Ваше тестовое. Поэтому хотел поинтересоваться, как в у Вас всё прошло, удалось ли устроиться, если да, то как Вам компания?

**Comment by eduard-vm** [comment]
Нет, устроится не получилось - после интервью с CTO появилось понимание, что это не та команда и рабочие отношения в которых я хочу как-либо участвовать. А HR-менеджер вам никакой информации не дала?

**Comment by marker-dao** [comment]
К сожалению, полной информации, которая подтверждает красивые слова hr, я от него не получил. Что ж, спасибо за мнение. Предлагаю закрыть вопрос)
